"""
Mensagem de entrada
"""
input ConsumerMessageInput {
  msg: String
}

"""
Message de resultado
"""
type ConsumerMessageResult {
  id: String
  message: String
}

type Query {
  """
  #### Versão do serviço de rabbitmq consumer
  """
  versionRabbitMQConsumer: String
  """
  #### Resultado
  """
  getMessage: ConsumerMessageResult
  getAllMessages: [ConsumerMessageResult]
}

type Mutation {
  sendMessage(input: ConsumerMessageInput): String
}
