"""
Mensagem de entrada
"""
input MessageInput {
  msg: String
}

"""
Message de resultado
"""
type MessageResult {
  id: String
  message: String
}

type Query {
  """
  # Resultado
  """
  getMessage: MessageResult
  getAllMessages: [MessageResult]
}

type Mutation {
  sendMessage(input: MessageInput): String
}
